# This is a config for E2B sandbox template.
# You can use template ID (tm1rezbtu9zx9kfzgozm) or template name (reactwrite-ai-coding) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("reactwrite-ai-coding") # Sync sandbox
# sandbox = await AsyncSandbox.create("reactwrite-ai-coding") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('reactwrite-ai-coding')

dockerfile = "e2b.Dockerfile"
template_name = "reactwrite-ai-coding"
template_id = "tm1rezbtu9zx9kfzgozm"
