name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    # these are placeholders which is fine for integration tests
    env:
      KV_URL: redis://localhost:6379
      KV_REST_API_READ_ONLY_TOKEN: test-read-only-token
      KV_REST_API_TOKEN: test-api-token
      KV_REST_API_URL: https://test-kv-api.example.com
      SUPABASE_SERVICE_ROLE_KEY: test-service-role-key
      INFRA_API_URL: https://api.e2b-test.dev
      BILLING_API_URL: https://billing.e2b-test.dev
      NEXT_PUBLIC_POSTHOG_KEY: test-posthog-key
      NEXT_PUBLIC_SUPABASE_URL: https://test-supabase-url.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY: test-supabase-anon-key
      NEXT_PUBLIC_STRIPE_BILLING_URL: https://test-stripe-billing.example.com
      NEXT_PUBLIC_SCAN: 0
      NEXT_PUBLIC_MOCK_DATA: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run integration tests
        run: bun test:integration
